import { ThemeName } from '@/types'

export interface ThemeConfig {
  name: ThemeName
  label: string
  description: string
  emoji: string
  preview: {
    bg: string
    card: string
    accent: string
    text: string
  }
  cssVars: Record<string, string>
  fontFamily?: string
  bodyClass?: string
}

export const themes: ThemeConfig[] = [
  {
    name: 'bright-glass',
    label: 'Bright Glass',
    description: 'Cerah, ceria, glassmorphism terang — default MemoryVault',
    emoji: '✨',
    preview: { bg: '#e0f2fe', card: 'rgba(255,255,255,0.7)', accent: '#06b6d4', text: '#1e293b' },
    cssVars: {
      '--bg-primary': 'linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 40%, #f5f3ff 100%)',
      '--bg-secondary': 'rgba(255,255,255,0.6)',
      '--bg-tertiary': 'rgba(241,245,249,0.8)',
      '--bg-card': 'rgba(255,255,255,0.7)',
      '--bg-hover': 'rgba(6,182,212,0.06)',
      '--accent': '#06b6d4',
      '--accent-light': '#22d3ee',
      '--accent-dark': '#0891b2',
      '--text-primary': '#1e293b',
      '--text-secondary': '#475569',
      '--text-muted': '#94a3b8',
      '--border': 'rgba(6,182,212,0.2)',
      '--border-light': 'rgba(6,182,212,0.1)',
      '--success': '#10b981',
      '--warning': '#f59e0b',
      '--error': '#ef4444',
      '--shadow': '0 4px 24px rgba(6,182,212,0.15)',
    },
    bodyClass: 'theme-light',
  },
  {
    name: 'dark-minimal',
    label: 'Dark Minimal',
    description: 'Hitam pekat, tipografi bersih, aksen ungu',
    emoji: '🌑',
    preview: { bg: '#0a0a0f', card: '#12121a', accent: '#7c5cfc', text: '#e2e2ff' },
    cssVars: {
      '--bg-primary': '#0a0a0f',
      '--bg-secondary': '#12121a',
      '--bg-tertiary': '#1a1a28',
      '--bg-card': '#12121a',
      '--bg-hover': '#1e1e2e',
      '--accent': '#7c5cfc',
      '--accent-light': '#9d7dff',
      '--accent-dark': '#5a3fd0',
      '--text-primary': '#e2e2ff',
      '--text-secondary': '#a0a0c0',
      '--text-muted': '#606080',
      '--border': '#2a2a40',
      '--border-light': '#3a3a55',
      '--success': '#4ade80',
      '--warning': '#fbbf24',
      '--error': '#f87171',
      '--shadow': '0 4px 24px rgba(124,92,252,0.15)',
    },
  },
  {
    name: 'dark-glassmorphism',
    label: 'Dark Glassmorphism',
    description: 'Blur glass cards, gradient background gelap',
    emoji: '🔮',
    preview: { bg: '#0d1117', card: 'rgba(255,255,255,0.05)', accent: '#60a5fa', text: '#f0f6ff' },
    cssVars: {
      '--bg-primary': '#0d1117',
      '--bg-secondary': '#161b22',
      '--bg-tertiary': '#21262d',
      '--bg-card': 'rgba(255,255,255,0.04)',
      '--bg-hover': 'rgba(255,255,255,0.08)',
      '--accent': '#60a5fa',
      '--accent-light': '#93c5fd',
      '--accent-dark': '#3b82f6',
      '--text-primary': '#f0f6ff',
      '--text-secondary': '#8b949e',
      '--text-muted': '#484f58',
      '--border': 'rgba(255,255,255,0.08)',
      '--border-light': 'rgba(255,255,255,0.15)',
      '--success': '#4ade80',
      '--warning': '#fbbf24',
      '--error': '#f87171',
      '--shadow': '0 8px 32px rgba(0,0,0,0.5)',
      '--glass-blur': '12px',
    },
    bodyClass: 'theme-glass',
  },
  {
    name: 'light-clean',
    label: 'Light Clean',
    description: 'Putih bersih, shadow lembut, serif typography',
    emoji: '☀️',
    preview: { bg: '#ffffff', card: '#f8fafc', accent: '#4f46e5', text: '#1e293b' },
    cssVars: {
      '--bg-primary': '#ffffff',
      '--bg-secondary': '#f8fafc',
      '--bg-tertiary': '#f1f5f9',
      '--bg-card': '#ffffff',
      '--bg-hover': '#f8fafc',
      '--accent': '#4f46e5',
      '--accent-light': '#6366f1',
      '--accent-dark': '#3730a3',
      '--text-primary': '#1e293b',
      '--text-secondary': '#64748b',
      '--text-muted': '#94a3b8',
      '--border': '#e2e8f0',
      '--border-light': '#f1f5f9',
      '--success': '#16a34a',
      '--warning': '#d97706',
      '--error': '#dc2626',
      '--shadow': '0 2px 16px rgba(0,0,0,0.08)',
    },
    fontFamily: 'Lora, Georgia, serif',
    bodyClass: 'theme-light',
  },
  {
    name: 'light-paper',
    label: 'Light Paper',
    description: 'Krem/warm white, feels like a notebook',
    emoji: '📄',
    preview: { bg: '#faf7f2', card: '#f5f0e8', accent: '#b45309', text: '#292524' },
    cssVars: {
      '--bg-primary': '#faf7f2',
      '--bg-secondary': '#f5f0e8',
      '--bg-tertiary': '#ede9df',
      '--bg-card': '#faf7f2',
      '--bg-hover': '#f0ebe0',
      '--accent': '#b45309',
      '--accent-light': '#d97706',
      '--accent-dark': '#92400e',
      '--text-primary': '#292524',
      '--text-secondary': '#78716c',
      '--text-muted': '#a8a29e',
      '--border': '#e7e0d5',
      '--border-light': '#ede9df',
      '--success': '#15803d',
      '--warning': '#b45309',
      '--error': '#b91c1c',
      '--shadow': '0 2px 12px rgba(41,37,36,0.08)',
    },
    bodyClass: 'theme-light',
  },
  {
    name: 'cyberpunk',
    label: 'Cyberpunk',
    description: 'Neon green/cyan di background hitam',
    emoji: '⚡',
    preview: { bg: '#000a05', card: '#001a0a', accent: '#00ff41', text: '#00ff41' },
    cssVars: {
      '--bg-primary': '#000a05',
      '--bg-secondary': '#001a0a',
      '--bg-tertiary': '#002010',
      '--bg-card': '#001a0a',
      '--bg-hover': '#003020',
      '--accent': '#00ff41',
      '--accent-light': '#39ff6a',
      '--accent-dark': '#00cc33',
      '--text-primary': '#00ff41',
      '--text-secondary': '#00aa2b',
      '--text-muted': '#006620',
      '--border': '#004020',
      '--border-light': '#00602e',
      '--success': '#00ff41',
      '--warning': '#ffff00',
      '--error': '#ff0040',
      '--shadow': '0 0 20px rgba(0,255,65,0.2)',
      '--neon-glow': '0 0 10px rgba(0,255,65,0.5)',
    },
    fontFamily: 'JetBrains Mono, Fira Code, monospace',
    bodyClass: 'theme-cyberpunk',
  },
  {
    name: 'forest',
    label: 'Forest',
    description: 'Hijau sage, earthy tones, organic feel',
    emoji: '🌿',
    preview: { bg: '#1a2218', card: '#212e1f', accent: '#6aa84f', text: '#d4e6cc' },
    cssVars: {
      '--bg-primary': '#1a2218',
      '--bg-secondary': '#212e1f',
      '--bg-tertiary': '#283826',
      '--bg-card': '#212e1f',
      '--bg-hover': '#2e4029',
      '--accent': '#6aa84f',
      '--accent-light': '#8bc474',
      '--accent-dark': '#4d7a38',
      '--text-primary': '#d4e6cc',
      '--text-secondary': '#8aab7e',
      '--text-muted': '#4d6646',
      '--border': '#2e4029',
      '--border-light': '#3a5235',
      '--success': '#6aa84f',
      '--warning': '#d4a843',
      '--error': '#c0392b',
      '--shadow': '0 4px 20px rgba(0,0,0,0.4)',
    },
  },
  {
    name: 'ocean',
    label: 'Ocean',
    description: 'Biru deep, gradients biru-teal, calm',
    emoji: '🌊',
    preview: { bg: '#0a1628', card: '#0d1f3c', accent: '#38bdf8', text: '#e0f2fe' },
    cssVars: {
      '--bg-primary': '#0a1628',
      '--bg-secondary': '#0d1f3c',
      '--bg-tertiary': '#112550',
      '--bg-card': '#0d1f3c',
      '--bg-hover': '#163060',
      '--accent': '#38bdf8',
      '--accent-light': '#7dd3fc',
      '--accent-dark': '#0284c7',
      '--text-primary': '#e0f2fe',
      '--text-secondary': '#7dd3fc',
      '--text-muted': '#2563eb',
      '--border': '#1e3a6e',
      '--border-light': '#2563a8',
      '--success': '#34d399',
      '--warning': '#fbbf24',
      '--error': '#f87171',
      '--shadow': '0 4px 24px rgba(56,189,248,0.15)',
    },
  },
  {
    name: 'sunset',
    label: 'Sunset',
    description: 'Coral, orange, warm gradients',
    emoji: '🌅',
    preview: { bg: '#1a0a0a', card: '#2d1515', accent: '#f97316', text: '#fde8d8' },
    cssVars: {
      '--bg-primary': '#1a0a0a',
      '--bg-secondary': '#2d1515',
      '--bg-tertiary': '#3d1f1f',
      '--bg-card': '#2d1515',
      '--bg-hover': '#4d2828',
      '--accent': '#f97316',
      '--accent-light': '#fb923c',
      '--accent-dark': '#ea580c',
      '--text-primary': '#fde8d8',
      '--text-secondary': '#fdba74',
      '--text-muted': '#c2410c',
      '--border': '#4d2828',
      '--border-light': '#6b3a3a',
      '--success': '#86efac',
      '--warning': '#fbbf24',
      '--error': '#f87171',
      '--shadow': '0 4px 24px rgba(249,115,22,0.2)',
    },
  },
  {
    name: 'nord',
    label: 'Nord',
    description: 'Arctic blue, grey palette',
    emoji: '❄️',
    preview: { bg: '#2e3440', card: '#3b4252', accent: '#88c0d0', text: '#eceff4' },
    cssVars: {
      '--bg-primary': '#2e3440',
      '--bg-secondary': '#3b4252',
      '--bg-tertiary': '#434c5e',
      '--bg-card': '#3b4252',
      '--bg-hover': '#4c566a',
      '--accent': '#88c0d0',
      '--accent-light': '#8fbcbb',
      '--accent-dark': '#5e81ac',
      '--text-primary': '#eceff4',
      '--text-secondary': '#d8dee9',
      '--text-muted': '#4c566a',
      '--border': '#434c5e',
      '--border-light': '#4c566a',
      '--success': '#a3be8c',
      '--warning': '#ebcb8b',
      '--error': '#bf616a',
      '--shadow': '0 4px 20px rgba(0,0,0,0.3)',
    },
  },
  {
    name: 'dracula',
    label: 'Dracula',
    description: 'Purple, pink, yellow — klasik Dracula',
    emoji: '🧛',
    preview: { bg: '#282a36', card: '#1e1f29', accent: '#bd93f9', text: '#f8f8f2' },
    cssVars: {
      '--bg-primary': '#282a36',
      '--bg-secondary': '#1e1f29',
      '--bg-tertiary': '#21222c',
      '--bg-card': '#1e1f29',
      '--bg-hover': '#313341',
      '--accent': '#bd93f9',
      '--accent-light': '#caa9fd',
      '--accent-dark': '#9d74f7',
      '--text-primary': '#f8f8f2',
      '--text-secondary': '#6272a4',
      '--text-muted': '#44475a',
      '--border': '#44475a',
      '--border-light': '#6272a4',
      '--success': '#50fa7b',
      '--warning': '#f1fa8c',
      '--error': '#ff5555',
      '--shadow': '0 4px 20px rgba(0,0,0,0.4)',
    },
  },
  {
    name: 'solarized',
    label: 'Solarized',
    description: 'Warm amber, teal accents',
    emoji: '🌤️',
    preview: { bg: '#002b36', card: '#073642', accent: '#2aa198', text: '#fdf6e3' },
    cssVars: {
      '--bg-primary': '#002b36',
      '--bg-secondary': '#073642',
      '--bg-tertiary': '#004052',
      '--bg-card': '#073642',
      '--bg-hover': '#094e60',
      '--accent': '#2aa198',
      '--accent-light': '#40c9bf',
      '--accent-dark': '#1f7972',
      '--text-primary': '#fdf6e3',
      '--text-secondary': '#93a1a1',
      '--text-muted': '#657b83',
      '--border': '#094e60',
      '--border-light': '#0a5f74',
      '--success': '#859900',
      '--warning': '#cb4b16',
      '--error': '#dc322f',
      '--shadow': '0 4px 20px rgba(0,0,0,0.4)',
    },
  },
  {
    name: 'monochrome',
    label: 'Monochrome',
    description: 'Hitam putih murni, sangat minimal',
    emoji: '⬛',
    preview: { bg: '#000000', card: '#111111', accent: '#ffffff', text: '#ffffff' },
    cssVars: {
      '--bg-primary': '#000000',
      '--bg-secondary': '#111111',
      '--bg-tertiary': '#1a1a1a',
      '--bg-card': '#111111',
      '--bg-hover': '#222222',
      '--accent': '#ffffff',
      '--accent-light': '#e0e0e0',
      '--accent-dark': '#aaaaaa',
      '--text-primary': '#ffffff',
      '--text-secondary': '#888888',
      '--text-muted': '#444444',
      '--border': '#2a2a2a',
      '--border-light': '#3a3a3a',
      '--success': '#aaffaa',
      '--warning': '#ffddaa',
      '--error': '#ffaaaa',
      '--shadow': '0 4px 20px rgba(255,255,255,0.05)',
    },
  },
  {
    name: 'rose-gold',
    label: 'Rose Gold',
    description: 'Pink blush, gold accent, elegant',
    emoji: '🌸',
    preview: { bg: '#1a0f14', card: '#261520', accent: '#f4a261', text: '#fce8ec' },
    cssVars: {
      '--bg-primary': '#1a0f14',
      '--bg-secondary': '#261520',
      '--bg-tertiary': '#331c2a',
      '--bg-card': '#261520',
      '--bg-hover': '#3d2233',
      '--accent': '#f4a261',
      '--accent-light': '#e9c46a',
      '--accent-dark': '#e76f51',
      '--text-primary': '#fce8ec',
      '--text-secondary': '#e8a0b4',
      '--text-muted': '#8b4a62',
      '--border': '#3d2233',
      '--border-light': '#4f2d42',
      '--success': '#8fbc94',
      '--warning': '#e9c46a',
      '--error': '#e63946',
      '--shadow': '0 4px 24px rgba(244,162,97,0.15)',
    },
  },
  {
    name: 'terminal',
    label: 'Terminal',
    description: 'Full terminal look, green on black',
    emoji: '💻',
    preview: { bg: '#000000', card: '#0a0a0a', accent: '#33ff00', text: '#33ff00' },
    cssVars: {
      '--bg-primary': '#000000',
      '--bg-secondary': '#0a0a0a',
      '--bg-tertiary': '#0f0f0f',
      '--bg-card': '#0a0a0a',
      '--bg-hover': '#141414',
      '--accent': '#33ff00',
      '--accent-light': '#66ff33',
      '--accent-dark': '#22aa00',
      '--text-primary': '#33ff00',
      '--text-secondary': '#22aa00',
      '--text-muted': '#116600',
      '--border': '#1a3300',
      '--border-light': '#225500',
      '--success': '#33ff00',
      '--warning': '#ffff00',
      '--error': '#ff3300',
      '--shadow': '0 0 15px rgba(51,255,0,0.15)',
      '--neon-glow': '0 0 8px rgba(51,255,0,0.4)',
    },
    fontFamily: 'JetBrains Mono, Fira Code, monospace',
    bodyClass: 'theme-terminal',
  },
]

export const defaultSettings = {
  theme: 'bright-glass' as ThemeName,
  similarity_threshold: 0.7,
  max_memories_retrieve: 5,
  wake_word_sensitivity: 0.5,
  wake_word_custom: 'hey memory',
  tts_rate: 1.0,
  tts_pitch: 1.0,
  tts_volume: 1.0,
  default_view: 'grid' as const,
  sidebar_mode: 'expanded' as const,
  font_size: 'medium' as const,
  animation: 'full' as const,
  language: 'id' as const,
  system_prompt: `Kamu adalah asisten memori pribadi. Jawab pertanyaan berdasarkan memories yang diberikan. Jawab dalam bahasa yang sama dengan pertanyaan. Jika tidak ada informasi relevan, katakan "Tidak ada ingatan tentang itu."`,
}

export function applyTheme(themeName: ThemeName): void {
  const theme = themes.find(t => t.name === themeName) || themes[0]
  const root = document.documentElement

  // Remove old theme classes
  root.classList.remove('theme-light', 'theme-glass', 'theme-cyberpunk', 'theme-terminal')

  // Apply CSS variables
  Object.entries(theme.cssVars).forEach(([key, value]) => {
    root.style.setProperty(key, value)
  })

  // Apply body class
  if (theme.bodyClass) {
    root.classList.add(theme.bodyClass)
  }

  // Apply font
  if (theme.fontFamily) {
    root.style.setProperty('--font-primary', theme.fontFamily)
  } else {
    root.style.setProperty('--font-primary', 'Inter, system-ui, sans-serif')
  }
}
